### ISSUE TITLE
Develop a way to automate release package

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Archive#18]
We should determine how we want to package OP2Archive for release.

Since OP2Archvie doesn't get released often, packaging doesn't need to be too automated or slick. Although it would be nice to somewhat script the process.

Preferably release packaging would be similar or same process for both Linux and Windows. I'd like the process to handle producing both x86 and x64 builds if possible (maybe testing if x64 is possible should come before this issue is resolved). I'd also like to produce symbol (debug info files) for storage with the builds for future debug usage.

Currently, there is a batch script located in the Visual Studio project file that handles Windows builds. See it below. Basic breakdown is:

 - Check if it is a release build and not a debug build
 - Create a directory named OP2Archive VerX.X.X
 - Create a directory named OP2Archive VerX.X.X_PDB (for debug symbols associated to release)
 - Copy ReadMe.txt, License.txt, and OP2Archive.exe into the created release directory.
 - Copy OP2Archive.pdb into the created symbols directory (PDB)
 - Zip both directories
 - Delete the 2 created directories

I think on Linux people usually name symbol files as .debug from some reading I did, but I'm not sure. It seems like the process may not be as robust on Linux as it is on Windows.

CMake's scripting system offers all the tools needed to reproduce this process in a cross platform manner with commands to manipulate files, directories, and create archives. I have a partially build script file that sort of duplicates the Windows batch script.

However, I realized that I think CMake's CMakeLists.txt only runs when its contents change, so placing a script file in there may not actually be appropriate? Or I don't know the best way to trigger it if we want to go with a script that just collects the files in a zip.

I'd like to explore using CMake's built in Versioning information. There is a way to create a new header file with the version information contained in it when a project is generated that I have played with. 

Anyways, just throwing some ideas out, but not sure what the final answer should be. 

I haven't explored CPack much yet, but I did the official CMake tutorial and it had a setup like this:

```
set (VERSION_MAJOR 1)
set (VERSION_MINOR 0)
set (VERSION_BUILD 12)

. . . 

# Cofigure header to pass Version Info into the source code
configure_file(
	"${PROJECT_SOURCE_DIR}/TutorialConfig.h.in"
	"${PROJECT_BINARY_DIR}/TutorialConfig.h"
)

# Add the binary tree to the search path for include files. (Allows finding Tutorial.Config.h)
include_directories("${PROJECT_BINARY_DIR}")

. . .

# Add install targets
install (TARGETS Tutorial DESTINATION bin)
install (FILES "${PROJECT_BINARY_DIR}/TutorialConfig.h" DESTINATION include)

include (InstallRequiredSystemLibraries)

set (CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/License.txt")
set (CPACK_PACKAGE_VERSION_MAJOR "${VERSION_MAJOR}")
set (CPACK_PACKAGE_VERSION_MINOR "${VERSION_MINOR}")

include (CPack)
```

Current Windows Batch ran as a post build event:

```
SET zipName="OP2Archive Ver1.1.1"
SET directoryName=$(OutDir)%25zipName%25 

SET pdbDirectoryName=$(OutDir)%25zipName%"_PDB"

if $(ConfigurationName) == Release (
    mkdir %25directoryName%25
    mkdir %25pdbDirectoryName%25 

    xcopy /y /d "$(ProjectDir)ReadMe.txt" %25directoryName%25
    xcopy /y /d "$(ProjectDir)License.txt" %25directoryName%25
    xcopy /y /d "$(OutDir)$(TargetFileName)" %25directoryName%25

    xcopy /y /d "$(OutDir)OP2Archive.pdb" %25pdbDirectoryName%25

    REM Use 7Zip to zip final version
    7za a -tzip $(OutDir)%25zipName%25.zip %25directoryName%25
    
    DEL /q %25directoryName%25\*.*
    RMDIR %25directoryName%25 /s /q

    7za a -tzip $(OutDir)%25zipName%25"_PDB".zip %25pdbDirectoryName%25
    DEL /q %25pdbDirectoryName%25\*.*
    RMDIR %25pdbDirectoryName%25 /s /q
)
```

**Comment by DanRStevens** [comment]
It would be nice to automate this just so we have the experience with automated deployments.

I assume you mean have separate packages for each system, rather than one package with the files for all systems. I suppose we could do it either way, but currently we don't have cross compiling working, so we'd need multiple systems to prepare packages for both Windows and Linux.

I assume there must be a way to have CMake output scripts to the Makefile, or to the Visual Studio project file's post build events. The script might exist in CMakeLists.txt, but perhaps it is translated into a form suitable to run by the build system. Looks like there is an [`add_custom_command`](https://cmake.org/cmake/help/v2.8.8/cmake.html#command:add_custom_command).

I saw an article on using Git tags with CMake versioning. It might be nice to combine that with the header files to inject version numbers into final output programs.
[CMake: Automatically use git tags as version strings](http://ipenguin.ws/2012/11/cmake-automatically-use-git-tags-as.html)

I think it's fine if we leave the old project files around for a little while so we have time to settle into the new build system.

**Comment by Brett208** [comment]
Yeah, I'm not ready to attempt building releases on one platform for another platform. I was more talking about standardizing the process between platforms. So when you build a Linux release, it runs the same (or close to the same) script as I would use on Windows. This way when we want to update the release process, it just has to be manipulated in one place.

The post to Brian Milco's blog looks pretty sound. I think that I like pulling the Git tag into CMake for release packaging. This would force someone to add a tag before releasing any package, which seems like a good thing. His solution is also pushing the version into the source code using a header file which seems to be an established process I've seen in other places.

**Comment by Brett208** [comment]
I've been researching this some more. It looks like CPack can package a release into a zip file. That zip file can contain the compiled executable and other specified files such as ReadMe.txt and License.txt.

You run CPack from the command line just as you would run CMake. So, you would run CMake to generate the build process. Then when ready for release, you would run CPack. It might be possible to compile the source code through CPack by specifying a generator, although I haven't played with it enough to understand the details.

You can specify the variables for CPack inside the CMakeLists.txt or in a separate file called CPackConfig.cmake. I think it makes sense to me to put the packaging information in a separate file from the platform build generation tool. I haven't figured out how feasible it is to share version information between CMakeLists.txt and CPackConfig.cmake. 

I'm having trouble finding good introduction articles on CPack. Below seem to be some of the better sources.

https://gitlab.kitware.com/cmake/community/wikis/doc/cpack/Packaging-With-CPack
https://gitlab.kitware.com/cmake/community/wikis/doc/cpack/PackageGenerators

-Brett

**Comment by DanRStevens** [comment]
Thanks for the links.

Perhaps as an intermediate step, we can take the current Visual Studio project's post build steps, and incorporate them into the CMake file, such than when generating Visual Studio projects, it re-creates the current post build steps. There is a StackOverflow question on using [CMake to add Visual Studio project custom build events](https://stackoverflow.com/questions/7988297/cmake-to-add-vs2010-project-custom-build-events).

I know that wouldn't be a very cross platform way to package a release, but I think it might be a quick way to get the CMake generated Visual Studio project up to the same level as the existing Visual Studio project. That would ease commitment to the new process.

This CPack stuff sounds like a more cross platform solution, though it also looks considerably more complicated, and I'm afraid I find a lot of the CMake related documentation a bit dry.

I guess I'm concerned about losing momentum on some of this CMake stuff. Seems like porting the Windows release packaging post build steps to CMake would be a good enough solution that would be faster and easier to implement, and gets us more used to tools that might provide a better next solution. Plus, I would just enjoy seeing the old system replicated with CMake, and the process documented as part of project history.
